services:
  # PostgreSQL Database with pgcrypto extension
  dspace-db:
    image: postgres:17
    container_name: dspace-postgres
    environment:
      POSTGRES_DB: dspace
      POSTGRES_USER: dspace
      POSTGRES_PASSWORD: dspace
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-extensions.sql:/docker-entrypoint-initdb.d/01-init-extensions.sql
      - ./docker/postgres/init-dspace.sql:/docker-entrypoint-initdb.d/02-init-dspace.sql
    networks:
      - dspace-network
    restart: unless-stopped

  # Apache Solr 9.x for search indexing
  dspace-solr:
    image: solr:9.8
    container_name: dspace-solr
    environment:
      SOLR_OPTS: "-Dsolr.config.lib.enabled=true"
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
      - ./docker/solr/configsets:/opt/solr/server/solr/configsets:ro
    command: |
      bash -c "
        solr-foreground &
        sleep 30
        # Create DSpace cores using our custom configurations
        solr create_core -c search -d /opt/solr/server/solr/configsets/search || true
        solr create_core -c statistics -d /opt/solr/server/solr/configsets/statistics || true
        solr create_core -c authority -d /opt/solr/server/solr/configsets/authority || true
        wait
      "
    networks:
      - dspace-network
    restart: unless-stopped

  # DSpace Backend - Built from Dockerfile
  dspace-backend:
    build:
      context: .
      dockerfile: ./docker/dspace-backend/Dockerfile
    container_name: dspace-backend
    ports:
      - "8080:8080"
    volumes:
      - dspace_install:/dspace
      - dspace_logs:/dspace/log
      - ./dspace-source:/dspace-source # Mount local source for development
    networks:
      - dspace-network
    depends_on:
      dspace-db:
        condition: service_started
      dspace-solr:
        condition: service_started
    environment:
      POSTGRES_HOST: "dspace-db"
      POSTGRES_DB: "dspace"
      POSTGRES_USER: "dspace"
      POSTGRES_PASSWORD: "dspace"
      SOLR_HOST: "dspace-solr"
      SOLR_PORT: "8983"
      ADMIN_EMAIL: "admin@dspace.org"
      ADMIN_PASSWORD: "admin"
      JAVA_OPTS: "-Xmx2g -Xms1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
      SPRING_PROFILES_ACTIVE: "docker"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/server/api"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s

  # DSpace Frontend - Built from Dockerfile
  dspace-frontend:
    build:
      context: .
      dockerfile: ./docker/dspace-frontend/Dockerfile
      args:
        DSPACE_UI_HOST: "0.0.0.0"
        DSPACE_UI_PORT: "4000"
        DSPACE_REST_HOST: "dspace-backend"
        DSPACE_REST_PORT: "8080"
        DSPACE_REST_NAMESPACE: "/server"
        DSPACE_REST_SSL: "false"
    container_name: dspace-frontend
    ports:
      - "4000:4000"
    networks:
      - dspace-network
    volumes:
      - ./dspace-angular:/app # Mount local Angular source for development
    depends_on:
      dspace-backend:
        condition: service_healthy
    environment:
      NODE_ENV: "production"
      DSPACE_UI_HOST: "0.0.0.0"
      DSPACE_UI_PORT: "4000"
      DSPACE_REST_HOST: "dspace-backend"
      DSPACE_REST_PORT: "8080"
      DSPACE_REST_NAMESPACE: "/server"
      DSPACE_REST_SSL: "false"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  postgres_data:
  solr_data:
  dspace_install:
  dspace_logs:

networks:
  dspace-network:
    driver: bridge
